#!/usr/bin/env bash
#A Bash Script used to transfers a file from our client to a server:
#It accepts 4 parameters : path to the file being transfered,
#The IP of the server to transfer the file to,
#The username scp connects with,
#The path to the SSH private key that scp uses
#scp must transfer the file to the user home directory ~/
#Strict host key checking must be disabled when using scp
#Display Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY if less than 3 parameters passed
if [ $# -lt 4 ]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
        scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
