#!/usr/bin/env bash
# This is a Bash script that pings the specified IP address five times.
# Usage: 5-is_the_host_on_the_network {IP_ADDRESS}
if [ "$1" ]
then
ping -c 5 "$1"
else
echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi
