#!/usr/bin/env bash
# This Bash Script is used to manage the script 'manage_my_process' with start, stop, and restart functionality.
#   - `start`: Initiates 'manage_my_process', creates a PID file, and displays "manage_my_process started."
#   - `stop`: Terminates 'manage_my_process', deletes the PID file, and displays "manage_my_process stopped."
#   - `restart`: Stops and restarts 'manage_my_process', updates the PID file, and displays "manage_my_process restarted."
# If no or an invalid argument is provided, displays "Usage: manage_my_process {start|stop|restart}".

command="$1"

if [ -z "$command" ]; then
  echo "Usage: manage_my_process {start|stop|restart}"
  exit
fi

if [ "$command" == "start" ]; then
  # Start 'manage_my_process', create a PID file, and display success message.
  bash ./manage_my_process &
  echo "$!" > /var/run/my_process.pid
  echo "manage_my_process started"

elif [ "$command" == "stop" ]; then
   # Stop 'manage_my_process', delete the PID file, and display success message.
  [ -e "/var/run/my_process.pid" ] && pkill -f './manage_my_process' && rm /var/run/my_process.pid
  echo "manage_my_process stopped"

elif [ "$command" == "restart" ]; then
  # Restart 'manage_my_process', update the PID file, and display success message.
  "$0" stop >& /dev/null
  "$0" start >& /dev/null
  echo "manage_my_process restarted"

else
  echo "Usage: manage_my_process {start|stop|restart}"
fi
