#!/usr/bin/env bash
# This Bash Script terminates the process running the script '4-to_infinity_and_beyond'.
# Uses 'pgrep' to find the process ID (PID) and 'kill' to terminate it.
kill "$(pgrep -f 4-to_infinity_and_beyond)"
