#!/usr/bin/env bash
# This is a Bash script used to output "Best School" 10 times, appending "Hi" on a new line during the 9th iteration.
# Utilizes a while loop with a conditional check for the 9th iteration.
n=1

while [ $n -le 10 ]
do
    echo "Best School"
    if [ $n -eq 9 ]
    then
        echo "Hi"
    fi
    n=$(( n + 1 ))
done
