#!/usr/bin/env bash
# This is a Bash script used to display time in 12-hour format with 59 minutes.
# Employs a nested while loop structure: the outer loop iterates through hours (0 to 12),
# while the inner loop iterates through minutes (1 to 59) for each hour.
# Outputs the current hour and minute within the loops.
hour=0

while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]
    do
        echo $minute
        minute=$(( minute + 1 ))
    done
    hour=$(( hour + 1 ))
done
