#!/usr/bin/env bash
# This is a Bash script used to display information about the file 'school'.
# Checks if the file exists, and if so, examines whether it's empty or a regular file, printing corresponding messages.
# If the file doesn't exist, it notifies that the file is absent.
if [ -e "school" ]
then
  echo "school file exists"
  if [ -s "school" ]
  then
    echo "school file is not empty"
  else
    echo "school file is empty"
  fi

  if [ -f "school" ]
  then
    echo "school is a regular file"
  fi
else
  echo "school file does not exist"
fi
