#!/usr/bin/env bash
#This Bash Script Copies the current hosts file, updates it with a new IP address and hostname,
# and replaces the original /etc/hosts file with the modified version.
cp /etc/hosts ~/hosts.new
echo "127.0.0.2 localhost" > ~/hosts.new
echo "8.8.8.8  facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
